version: "3.5"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${BOOKSTACK_PUID}
      - PGID=${BOOKSTACK_PGID}
      - APP_URL=${BOOKSTACK_APP_URL}
      - DB_HOST=${BOOKSTACK_DB_HOST}
      - DB_USER=${BOOKSTACK_DB_USER}
      - DB_PASS=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=${BOOKSTACK_DB_DATABASE}
    volumes:
      - ./config:/config
    ports:
      - 80:80
    restart: unless-stopped
